{% set name = "ecs-logging" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1dc9e216f614129db0e6a2f9f926da4e4cf8edf8de16d1045a20aa8e950291d3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - flit >=2,<3
  run:
    - python >=3.3

test:
  imports:
    - ecs_logging
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/elastic/ecs-logging-python
  summary: Logging formatters for ECS (Elastic Common Schema) in Python
  dev_url: https://github.com/elastic/ecs-logging-python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - deantvv
